site_name: 미쁨에듀 블로그
site_description: Mippum's Blog from MD Files
site_author: mippum
site_url: https://mippum.github.io/mp-blog/

theme:
  name: material
  language: ko
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: brown
    accent: amber

plugins:
  - blog:
      folder: blog
      articles: 5
      format: "%Y-%m-%d"
      blog_dir: blog
      post_excerpt: optional
  - macros:
      module_name: main
  - search
  

extra_css:
  - stylesheets/extra.css

nav:
  - 홈: index.md
  - 블로그 글: blog/index.md
  - 소개 : about.md
